### ISSUE TITLE
All Colors Legend Typo

### ISSUE THREAD

**Issue by bhavelka** [Connor-Bayer/themeBayer#6]
For the plot showing all colors in the readme I noticed the legend has the hex# swapped for the green and purple indicated in attached image. The "mids" and "greens" plots in the readme have the hex# correct.
![Snap8](https://github.com/Connor-Bayer/themeBayer/assets/114951089/5a54bc50-3a95-4600-9f6f-fd6d2dc9bba6)

**Comment by Connor-Bayer** [comment]
Should be all resolved!

It's actually an issue with how ggplot re-orders data when displaying it - it helpfully sorted the hexes by alpha-numeric order, which disrupts the labels but not the colors.

Thank you so much for bringing this to my attention.
